### ISSUE TITLE
建议增加jsoniter中Stream方案的等价结构序列化性能比较

### ISSUE THREAD

**Issue by szyhf** [darjun/json-gen#1]
目前你实现的方式，与标准包中的json实现逻辑差异比较大，性能差10倍属于正常操作，建议跟jsoniter-go中的Stream实现做一下比较，与你当前的实现比较类似，但它兼容性比你好，支持但不依赖扩展接口。

**Comment by darjun** [comment]
感谢指出，学习了。

增加了与`jsoniter/go`的比较，`jsoniter/go`性能确实棒。

我稍微看了一下stream的实现，高性能得益于它的缓存池。不过感觉stream的使用稍微有些麻烦，我的写法如果有什么不妥的往指出，感谢~

**Comment by szyhf** [comment]
客气啦，不是说你的实现有问题，只是感觉你的接口实现上类似Stream，如果要做性能比较的话可以追加一个比较，这样比较完备一些~

例如：

```golang
// 你的实现
a := jsongen.NewArray()
a.AppendUint(123)
a.AppendInt(-456)
data := a.Serialize(nil)
// 等价的Stream实现
bf := bytes.NewBuffer(nil)
js := jsoniter.ConfigFastest.BorrowStream(bf)
js.WriteArrayStart()
js.WriteInt64(123)
js.WriteMore()
js.WriteInt(-456)
js.WriteArrayEnd()
data := bf.Bytes()
```

当然，它的实现跟你是不一样的，就是觉得补充一个比较会比较好~~
